name: Test and Coverage Check

on:
  push:
    branches:
      - main  

jobs:
  test-and-check-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run tests and generate coverage
        run: npm test -- --coverage --collectCoverageFrom=src/**/*.js

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3.1.4
        env:
          CODECOV_TOKEN: da850676-620c-4fef-bdf4-9360e3e02ba7
        with:
          file: ./coverage/lcov.info
